import React from "react";
import { GlassPanel } from "@/components/compsphere/GlassPanel";
import { Bell, ShieldAlert } from "lucide-react";

export function Announcements() {
  const announcements = [
    {
      title: "Deliverables Submission Portal Open!",
      date: "Oct 6, 2026",
      desc: "Verified teams can now submit repository URLs and presentation slides. Note that updates are allowed up until the hard lock on Oct 11, 10:00 AM Asia/Jakarta.",
      pinned: true,
    },
    {
      title: "Google Authentication Onboarding Guidelines",
      date: "Oct 1, 2026",
      desc: "All participants must sign in with their Google accounts. If you are a team leader, enter the access token printed on your administrative migration sheet to unlock your workspace. Team members can join via the invite links generated by leaders.",
      pinned: false,
    },
    {
      title: "Verification Windows & Waitlist Claims",
      date: "Sep 28, 2026",
      desc: "Qualified teams have exactly 48 hours to confirm their participation. Unconfirmed slots will automatically be dropped and opened to waitlist ranks 31-40 via the Battle Royale portal.",
      pinned: false,
    },
  ];

  return (
    <div className="space-y-12 max-w-2xl mx-auto py-6">
      <div className="space-y-4 text-center">
        <div className="w-12 h-12 rounded-full bg-brand-dim border border-brand-primary/20 flex items-center justify-center mx-auto text-brand-primary">
          <Bell className="w-6 h-6 animate-bounce" />
        </div>
        <h1 className="text-4xl font-extrabold text-glow text-text-primary">Announcements</h1>
        <p className="text-sm text-text-secondary">
          Stay updated with administrative guidelines, deadlines, and portal announcements.
        </p>
      </div>

      <div className="space-y-6">
        {announcements.map((item, idx) => (
          <GlassPanel key={idx} className={item.pinned ? "border-brand-primary/30" : "border-border"}>
            <div className="flex gap-4">
              <div className="w-8 h-8 rounded-lg bg-bg-surface border border-border flex items-center justify-center text-brand-primary shrink-0">
                {item.pinned ? <ShieldAlert className="w-4 h-4 text-brand-accent" /> : <Bell className="w-4 h-4 text-text-secondary" />}
              </div>
              <div className="space-y-2 flex-1">
                <div className="flex justify-between items-baseline gap-2 flex-wrap">
                  <h3 className="font-bold text-sm text-text-primary">{item.title}</h3>
                  <span className="text-[10px] font-semibold text-text-muted">{item.date}</span>
                </div>
                <p className="text-xs text-text-secondary leading-relaxed">{item.desc}</p>
                {item.pinned && (
                  <span className="inline-block text-[9px] font-bold text-brand-accent bg-brand-dim px-2 py-0.5 rounded uppercase mt-2">
                    Pinned Announcement
                  </span>
                )}
              </div>
            </div>
          </GlassPanel>
        ))}
      </div>
    </div>
  );
}
